<?php

// Require WP Load First
$current_url = dirname( __FILE__ );
$wp_content_pos = strpos( $current_url, 'wp-content' );
$wp_content = substr( $current_url, 0, $wp_content_pos );
require_once( $wp_content . 'wp-load.php' );

// Revert Back to Stylesheet
ob_start ( "ob_gzhandler" );
header( "Content-type: text/css; charset: UTF-8" );

// Grab the HEX color value from theme options
$accent = get_theme_mod('link_accent_color', of_get_option( 'accent-color' ));
$portbg = of_get_option( 'portfolio-bkground-custom' );

?>


/*-----------------------------------------------------------------
 These are dynamic accent color values generated by theme options
-----------------------------------------------------------------*/

a {
	color: <?php echo $accent; ?>;
	}
	
a:hover {
	border: <?php echo $accent; ?>;
	}
	
::selection { 
	background: <?php echo $accent; ?>;
	}

a.btn,
input[type="submit"],
button.btn,
.more-link,
.search-form .search-submit {
	background-color: <?php echo $accent; ?>;
	}
	
#header .logo a {
	border-color: <?php echo $accent; ?>;
	}
		
#header #nav li.current_page_item a, 
#header #nav li.current-menu-parent a,
#header #nav li.current_page_parent a {
	color: <?php echo $accent; ?>;
	}

#header #nav ul a:hover,
#header #nav ul ul a:hover,
#header #nav li a:hover {
	color: <?php echo $accent; ?> !important;
	}

#header #nav ul li.current-menu-item a {
	color: <?php echo $accent; ?> !important;
	}

.slicknav_nav .slicknav_arrow {
	color: <?php echo $accent; ?> !important;
	}

body.home #columns span,
#blog .post span {
	background-color: <?php echo $accent; ?>;
	}

body.home #columns h2 {
	color: <?php echo $accent; ?> ;
	}
	
#portfolio .post a .overlay {
	background: <?php echo $accent; ?>;
	}

#portfolio .post a:hover .overlay {
	background: <?php echo $accent; ?>;
	}

#portfolio h2 a {
	color: <?php echo $accent; ?>;
	}

#portfolio .flexslider-home .flex-control-paging li a.flex-active {
	background: <?php echo $accent; ?>;
	}

body.home #portfolio .post a .overlay {
	background: <?php echo $accent; ?>;
	}
		
#blog .blog-heading h2 a,
#blog .post .entry-meta a {
	color: <?php echo $accent; ?>;
	}

#blog .post h2 a:hover {
	color: <?php echo $accent; ?>;
	}

#blog .post .entry-comments a {
	color: <?php echo $accent; ?>;
	}

#content article .entry-header h2.entry-title a:hover {
	color: <?php echo $accent; ?>;
	}

#content article .entry-content blockquote {
	border-left-color: <?php echo $accent; ?>;
	}

#content article.format-quote .entry-title a:hover blockquote p {
	color: <?php echo $accent; ?>;
	}

#content article.format-link .entry-image p a {
	background: <?php echo $accent; ?>;
	}

.mejs-time-current {
	background: <?php echo $accent; ?> !important;
	}

.mejs-controls .mejs-horizontal-volume-slider .mejs-horizontal-volume-current {
	background: <?php echo $accent; ?> !important;
	}

.flex-direction-nav a:hover {
	background-color: <?php echo $accent; ?>;
	}
	
body.single .entry-meta time, 
body.single .entry-meta span a {
	color: <?php echo $accent; ?>;
	}

#content .author-bio .author-name a,
#content #comments .comment-author cite {
	color: <?php echo $accent; ?>;
	}

.mighty_project_widget .post a .overlay {
	background: <?php echo $accent; ?>;
	}

.mighty_project_widget .post a:hover .overlay {
	background: <?php echo $accent; ?>;
	}

.mighty_social_widget a:hover {
	background: <?php echo $accent; ?>;
	}

body.page-template-template-portfolio-php .item a .overlay {
	background: <?php echo $accent; ?>;
	}

body.page-template-template-portfolio-php .item a:hover .overlay, 
body.page-template-template-portfolio-sortable-php .item a:hover .overlay, 
body.single-portfolio #portfolio .item a:hover .overlay {
	background: <?php echo $accent; ?>;
	}
	
body.page-template-template-portfolio-php #content h2.entry-title a,
body.page-template-template-portfolio-sortable-php #content h2.entry-title a {
	color: <?php echo $accent; ?>;
	}

body.page-template-template-portfolio-sortable-php .portfolio-filter li a.active,
body.page-template-template-portfolio-sortable-php .portfolio-filter li a:hover {
	color: <?php echo $accent; ?>;
	}

#footer #menu-text a:hover,
#footer .copyright a,
#footer #nav li a:hover,
#footer #nav ul a:hover, 
#footer #nav ul ul a:hover {
	color: <?php echo $accent; ?> !important;
	}

#footer .social-media i,
#footer .social-media a:hover {
	color: <?php echo $accent; ?>;	
	}

#footer li a {
	border-color: <?php echo $accent; ?>;
	}
	
#enews form input[type="submit"] {
	background-color: <?php echo $accent; ?>;
	}
	
.widget_categories li,
.widget_categories li a, 
.widget_archive li a { 
	color: <?php echo $accent; ?>;
	}

.widget_recent_entries li a:hover {
	color: <?php echo $accent; ?>;
	}

.widget_categories li a:hover {
	color: <?php echo $accent; ?>;
	}
